### ISSUE TITLE
support for backend 'jupyter_packaging.build_api'

### ISSUE THREAD

**Issue by bgerrity** [python-packaging/dowsing#53]
I'm trying to extract metadata for Jupyter Server and getting the error below. Seems like support is needed for the `jupyter_packaging.build_api` backend.

Happy to make this change myself if it's like adding support for [`poetry`](https://github.com/python-packaging/dowsing/commit/c53f3e80f9f21fa27766c06ee0cbf535e06d0521).

```
(dowsing) bgerrity@bgerrity-mbp dowsing % python3 -m dowsing.pep517 ~/jupyter_server/ | jq .
/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py:125: RuntimeWarning: 'dowsing.pep517' found in sys.modules after import of package 'dowsing', but prior to execution of 'dowsing.pep517'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/Users/bgerrity/dowsing/dowsing/pep517.py", line 39, in get_backend
    backend_path = KNOWN_BACKENDS[backend]
KeyError: 'jupyter_packaging.build_api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/bgerrity/dowsing/dowsing/pep517.py", line 89, in <module>
    main(Path(sys.argv[1]))
  File "/Users/bgerrity/dowsing/dowsing/pep517.py", line 78, in main
    metadata = get_metadata(path)
  File "/Users/bgerrity/dowsing/dowsing/pep517.py", line 67, in get_metadata
    _, backend = get_backend(path)
  File "/Users/bgerrity/dowsing/dowsing/pep517.py", line 41, in get_backend
    raise Exception(f"Unknown pep517 backend {backend!r}")
Exception: Unknown pep517 backend 'jupyter_packaging.build_api'
```

**Comment by thatch** [comment]
It looks like jupyter-packaging is still mostly setuptools (except for the yarn/npm bits).  I think it should be enough to add another entry near https://github.com/python-packaging/dowsing/blob/main/dowsing/pep517.py#L12 that maps it to SetuptoolsReader, can you give that a try?
