### ISSUE TITLE
Infinite recursion parsing setup.py from onnxruntime

### ISSUE THREAD

**Issue by amyreese** [python-packaging/dowsing#56]
Error occurs when trying to get metadata from git checkout of https://github.com/microsoft/onnxruntime.git

```
(.venv) jreese@butterfree ~/workspace/dowsing main  » python -m dowsing.pep517 ~/scratch/onnxruntime
/Users/jreese/.pyenv/versions/3.9.9/lib/python3.9/runpy.py:127: RuntimeWarning: 'dowsing.pep517' found in sys.modules after import of package 'dowsing', but prior to execution of 'd
owsing.pep517'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/Users/jreese/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jreese/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jreese/workspace/dowsing/dowsing/pep517.py", line 90, in <module>
    main(Path(sys.argv[1]))
  File "/Users/jreese/workspace/dowsing/dowsing/pep517.py", line 82, in main
    "get_requires_for_build_wheel": get_requires_for_build_wheel(path),
  File "/Users/jreese/workspace/dowsing/dowsing/pep517.py", line 62, in get_requires_for_build_wheel
    return requires + list(backend.get_requires_for_build_wheel())
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/__init__.py", line 32, in get_requires_for_build_wheel
    return ("setuptools", "wheel") + self._get_requires()
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/__init__.py", line 111, in _get_requires
    dist = self.get_metadata()
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/__init__.py", line 41, in get_metadata
    d2 = from_setup_py(self.path, {})
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 46, in from_setup_py
    wrapper.visit(analyzer)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/metadata/wrapper.py", line 207, in visit
    return self.module.visit(visitor)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/module.py", line 91, in visit
    result = super(Module, self).visit(visitor)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/module.py", line 75, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/internal.py", line 200, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/internal.py", line 172, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/statement.py", line 424, in _visit_and_replace_children
    body=visit_sequence(self, "body", self.body, visitor),
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/internal.py", line 156, in visit_sequence
    return tuple(visit_iterable(parent, fieldname, children, visitor))
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/internal.py", line 140, in visit_iterable
    new_child = child.visit(visitor)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/statement.py", line 331, in _visit_and_replace_children
    value=visit_required(self, "value", self.value, visitor),
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_nodes/base.py", line 216, in visit
    should_visit_children = visitor.on_visit(self)
  File "/Users/jreese/workspace/dowsing/.venv/lib/python3.9/site-packages/libcst/_visitors.py", line 123, in on_visit
    retval = visit_func(node)
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 160, in visit_Call
    value = self.evaluate_in_scope(arg.value, scope)
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 227, in evaluate_in_scope
    return self.evaluate_in_scope(gp.value, scope)
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 299, in evaluate_in_scope
    lhs = self.evaluate_in_scope(item.left, scope)
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 227, in evaluate_in_scope
    return self.evaluate_in_scope(gp.value, scope)
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 299, in evaluate_in_scope
    lhs = self.evaluate_in_scope(item.left, scope)
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 227, in evaluate_in_scope
    return self.evaluate_in_scope(gp.value, scope)
...
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 227, in evaluate_in_scope
    return self.evaluate_in_scope(gp.value, scope)
  File "/Users/jreese/workspace/dowsing/dowsing/setuptools/setup_py_parsing.py", line 186, in evaluate_in_scope
    elif isinstance(item, (cst.Integer, cst.Float)):
  File "/Users/jreese/.pyenv/versions/3.9.9/lib/python3.9/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by jreese** [comment]
With a bit of logging, this looks like dowsing is trying to evaluate `version_number = version_number + local_version` from the setup.py; because this is a self-referential assignment, `evaluate_in_scope` gets stuck in a loop trying to evaluate the BinaryOperation and the Name in the operation.

```
----- (507:21)
 Name(
    value='version_number',
    lpar=[],
    rpar=[],
) <libcst.metadata.scope_provider.GlobalScope object at 0x106141910>
----- (507:21)
 BinaryOperation(
    left=Name(
        value='version_number',
        lpar=[],
        rpar=[],
    ),
    operator=Add(
        whitespace_before=SimpleWhitespace(
            value=' ',
        ),
        whitespace_after=SimpleWhitespace(
            value=' ',
        ),
    ),
    right=Name(
        value='local_version',
        lpar=[],
        rpar=[],
    ),
    lpar=[],
    rpar=[],
) <libcst.metadata.scope_provider.GlobalScope object at 0x106141910>
left: Name(
    value='version_number',
    lpar=[],
    rpar=[],
)
----- (507:21)
 Name(
    value='version_number',
    lpar=[],
    rpar=[],
) <libcst.metadata.scope_provider.GlobalScope object at 0x106141910>
----- (507:21)
 BinaryOperation(
    left=Name(
        value='version_number',
        lpar=[],
        rpar=[],
    ),
    operator=Add(
        whitespace_before=SimpleWhitespace(
            value=' ',
        ),
        whitespace_after=SimpleWhitespace(
            value=' ',
        ),
    ),
    right=Name(
        value='local_version',
        lpar=[],
        rpar=[],
    ),
    lpar=[],
    rpar=[],
) <libcst.metadata.scope_provider.GlobalScope object at 0x106141910>
left: Name(
    value='version_number',
    lpar=[],
    rpar=[],
)
----- (507:21)
 Name(
    value='version_number',
    lpar=[],
    rpar=[],
) <libcst.metadata.scope_provider.GlobalScope object at 0x106141910>
```
